# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef24b83bed6dbbf0c8af32d7d200f32a0089675a17b7de8e453d84da133ae89360b1fa9a5da4b64fe4e275a58459f336700bded9489351b1ffabf19cf65eebfb

test:
  secret_key_base: 89e9dd44eee40cc70199ef9d610f55f90b1e3d34c357718f86f2409c4e00e72e9448a815a4a175a40cb5672445ed6684d1dc04be87c0ecb6db2be82a2d53bb45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
